"""Custom eSpeak-NG language builder for Sumerian and Akkadian.

eSpeak-NG supports custom language definitions. This module generates
the configuration files needed to create "Sumerian" and "Akkadian"
as eSpeak languages, providing more accurate pronunciation than
generic IPA input mode.

This is Path B of the ancient language pipeline.
"""

import logging
from pathlib import Path

from ancient.phonology import AKKADIAN_PHONOLOGY, SUMERIAN_PHONOLOGY

logger = logging.getLogger(__name__)


class ESpeakLanguageBuilder:
    """Generate eSpeak-NG language definition files."""

    def generate_phoneme_table(self, language: str = "akkadian") -> str:
        """Generate eSpeak phoneme table for a language.

        Args:
            language: "sumerian" or "akkadian"

        Returns:
            eSpeak phoneme table content
        """
        phonology = SUMERIAN_PHONOLOGY if language == "sumerian" else AKKADIAN_PHONOLOGY

        lines = [f"// eSpeak-NG phoneme definitions for {language.title()}"]
        lines.append("// Auto-generated by lotus-voice")
        lines.append("")

        # Vowels
        lines.append("// Vowels")
        for grapheme, ipa in phonology["vowels"].items():
            if len(grapheme) == 1:  # Skip long vowel digraphs
                lines.append(f"phoneme {ipa}")
                lines.append(f"  vowel starttype #{ipa} endtype #{ipa}")
                lines.append("  length 170")
                lines.append("endphoneme")
                lines.append("")

        # Long vowels
        lines.append("// Long vowels")
        for grapheme, ipa in phonology["vowels"].items():
            if "ː" in ipa:
                short = ipa.replace("ː", "")
                lines.append(f"phoneme {ipa}")
                lines.append(f"  vowel starttype #{short} endtype #{short}")
                lines.append("  length 300")
                lines.append("endphoneme")
                lines.append("")

        # Consonants
        lines.append("// Consonants")
        for grapheme, ipa in phonology["consonants"].items():
            if len(grapheme) <= 2:
                lines.append(f"phoneme {ipa}  // {grapheme}")
                lines.append("  // TODO: define articulation")
                lines.append("endphoneme")
                lines.append("")

        return "\n".join(lines)

    def generate_dictionary_rules(self, language: str = "akkadian") -> str:
        """Generate eSpeak letter-to-phoneme rules.

        These rules tell eSpeak how to pronounce each letter/digraph
        in the transliteration system.
        """
        phonology = SUMERIAN_PHONOLOGY if language == "sumerian" else AKKADIAN_PHONOLOGY

        lines = [f"// eSpeak dictionary rules for {language.title()}"]
        lines.append("// Maps transliteration graphemes to phonemes")
        lines.append("")

        all_mappings = {**phonology["consonants"], **phonology["vowels"]}

        # Sort by length descending (longer rules first)
        for grapheme in sorted(all_mappings.keys(), key=len, reverse=True):
            ipa = all_mappings[grapheme]
            lines.append(f".group {grapheme}")
            lines.append(f"  {grapheme}  {ipa}")
            lines.append("")

        return "\n".join(lines)

    def write_language_files(self, language: str, output_dir: Path):
        """Write eSpeak language definition files to disk."""
        output_dir.mkdir(parents=True, exist_ok=True)

        phonemes = self.generate_phoneme_table(language)
        rules = self.generate_dictionary_rules(language)

        (output_dir / f"ph_{language}").write_text(phonemes)
        (output_dir / f"{language}_rules").write_text(rules)

        logger.info(f"eSpeak language files written to {output_dir}")
